language: ruby
rvm:
  - 1.8.7
  - jruby-18mode
script: "rake spec_full"
branches:
  only:
    - master
env:
  matrix:
    - PUPPET_VERSION=2.7.13
    - PUPPET_VERSION=2.7.6
    - PUPPET_VERSION=2.6.9
  global:
    - PUBLISHER_LOGIN=rcoleman
    - secure: "XHHOkIpLKQe4Dz9pafncz1nlvok+B+iZs7H0nLvYKO5aJ3l7ZOvt8IjubMXV\nZZjDJAyBgDF2L/WWvWCIijjIvJJ5rmSbhEpgWm18w+nnlaRePyNOvIfq9iOA\nADbs2y4aqqtcdZ/LEkMV5R/HHL3BkbjTv9S7KewO6459DQTT+Pc="
notifications:
  email: false
gemfile: .gemfile
after_script:
- git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
- .forge-releng/publish
