language: ruby
rvm:
  - 1.8.7
  - jruby-18mode
script:
  - 'false'
  - git clone -q git://github.com/puppetlabs/ghpublisher.git .forge-releng
  - .forge-releng/publish
branches:
  only:
    - master
env:
  global:
    - PUBLISHER_LOGIN=rcoleman
    - secure: "Wq02qFt3Mlhx4bgy+Vs+jlf27WIQM+Z8yLJMusqiJcwaqBMwrCh0nK8Lj9oQ\nc31e8MbIuIRa9LIg30IWWe6jTw0n18K6kfQ6zhon6iWa+6w8w19iLetGA/14\nQi9u7rn9yePrHXtbIW9W7YfAmVVJts+Q637xgHyFXtXpaNEzrvA="
  matrix:
    - PUPPET_VERSION=2.7.13
notifications:
  email: false
gemfile: .gemfile
